# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'RWE Healthcare AI Services (bf9d5eae-bb3f-4a40-8b38-d61b8c8c0b70)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob download --container-name blobcontainer --file default.json --name "default.json" --account-key ${env:STORAGE_ACCOUNT_KEY}  --account-name nofandytestacct'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: ''
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/testgithub.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/testgithub.zip'
    ArtifactName: 'abc.zip'
